server:
  servlet:
    context-path: /blog
    session:
      timeout: 30
  port: 8080
  tomcat:
    uri-encoding: UTF-8


mybatis:
  type-aliases-package: com.newegg.mkpl.api.blogsystem.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


spring:
  datasource:
    url: jdbc:sqlserver://10.16.78.26:4433;databasename=intern_test;sendStringParametersAsUnicode=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: intern_test
    password: 123456


logging:
  config: classpath:log/log4j2.xml

user:
  account: 10086
  password: e10adc3949ba59abbe56e057f20f883e